version: '3'
services:
  frontend-service:
    build: ./packages/frontend/
    restart: unless-stopped
    volumes:
      - ./packages/frontend/public:/var/www/html
      - ./packages/frontend/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - web
    labels:
      - "traefik.http.routers.link-shortener-fe.rule=Host(`link-shortener.bilchuck.me`)"
      - "traefik.protocol=http"
      - "traefik.enable=true"
      - traefik.http.services.link-shortener-fe.loadbalancer.server.port=4200

  api-service:
    build: ./packages/api/
    volumes:
      - ./packages/api:/usr/app
      - /usr/app/node_modules
    environment:
      DB_HOST: postgres-db
      DB_NAME: link-shortener
      DB_USER: guest
      DB_PASS: guest
      DB_PORT: 5432
      DB_MIGRATIONS_RUN: 'true'
    networks:
      - web
    labels:
      - "traefik.http.routers.link-shortener-api.rule=Host(`lnk.bilchuck.me`)"
      - "traefik.protocol=http"
      - "traefik.enable=true"
      - traefik.http.services.link-shortener-api.loadbalancer.server.port=3000

  postgres-db:
    image: postgres:12
    volumes:
      - link-shortener__postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: link-shortener

volumes:
  link-shortener__postgres:

networks:
  web:
    external: true
