version: '3'
services:
  api-service:
    build: ./packages/api/
    volumes:
      - ./packages/api:/usr/app
      - /usr/app/node_modules
    command: yarn start:debug
    ports:
      - 3000:3000
      - 9229:9229 # for local debug
    environment:
      DB_HOST: postgres-db
      DB_NAME: link-shortener
      DB_USER: guest
      DB_PASS: guest
      DB_PORT: 5432
      DB_MIGRATIONS_RUN: 'true'

  postgres-db:
    image: postgres:12
    volumes:
      - link-shortener__postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: link-shortener

  postgres-db-adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: 'postgres-db'
      ADMINER_DESIGN: 'nette'

volumes:
  link-shortener__postgres:
